config/routes.rb
Hedemi::Application.routes.draw do
  resources :users

  get "users/new"

  match '/impressum', :to => 'pages#impressum'
  match '/haftungsausschluss', :to => 'pages#haftungsausschluss'
  match '/kontakt', :to => 'pages#kontakt'
  match '/vision', :to => 'pages#vision'
  match '/mitwirken', :to => 'pages#mitwirken'
  match '/agb', :to => 'pages#agb'
  match '/registrieren', :to => 'users#new'

end

app/models/user.rb
# == Schema Information
# Schema version: 20100812115939
#
# Table name: users
#
#  id         :integer(4)      not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class User < ActiveRecord::Base

  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation


  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, :presence => true,
  		   :length => { :maximum => 40 }
  validates :email, :presence => true,
                    :format   => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }
  # Automatically create the virtual attribute 'password_confirmation'.
  validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => { :within => 6..40 }

  before_save :encrypt_password

  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end

  private

    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def impressum
    @title = "Impressum"
  end

  def haftungsausschluss
    @title = "Haftungsausschluss"
  end

  def kontakt
    @title = "Kontakt"
  end

  def vision
    @title = "Vision"
  end

  def mitwirken
    @title = "Mitwirken"
  end

  def agb
    @title = "Allgemeine Geschaeftsbedingungen"
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
    @title = "Registrieren"
  end
  
  def show
    @user = User.find(params[:id])
    @title = @user.name
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to @user
      flash[:success] = "Registrierung erfolgreich!"
    else
      @user.password = ""
      @user.password_confirmation = ""
      @title = "Registrieren"
      render 'new'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Return a title on a per-page basis.
  def title
    base_title = "Herrscher des Mittelalters"
    if @title.nil?
      base_title
    else
      "#{@title} | #{base_title}"
    end
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>    
  
  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
  <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
  <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
  <%= stylesheet_link_tag 'custom', :media => 'screen' %>

  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
    <div class="container">
      <header>
       <%= image_tag("hedemi.png", :alt => "Herrscher des Mittelalters", :class => "round") %>
        <nav class="round">
          <ul>
            <li><%= link_to "Home", '#' %></li>
            <li><%= link_to "Anmelden", '#' %></li>
            <li><%= link_to "Vision", vision_path %></li>
            <li><%= link_to "Mitwirken", mitwirken_path %></li>
          </ul>
        </nav>
      </header>
      <section class="round">
      
      <div id="content" class="round">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, :class => "flash #{key}") %>
        <% end %> 
        <%= yield %>
      </div>

      </section>

<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "Kontakt", kontakt_path %></li>
      <li><%= link_to "Impressum", impressum_path %></li>
      <li><%= link_to "AGB", agb_path %></li>
      <li><%= link_to "Haftungsausschluss", haftungsausschluss_path %></li>
    </ul>
  </nav>
</footer>
<%= debug(params) if Rails.env.development? %>
    </div>
</body>
</html>

app/views/pages/agb.html.erb
<h1>Pages#agb</h1>
<p>Find me in app/views/pages/agb.html.erb</p>

app/views/pages/haftungsausschluss.html.erb
<h1>Pages#haftungsausschluss</h1>
<p>Find me in app/views/pages/haftungsausschluss.html.erb</p>

app/views/pages/impressum.html.erb
<h1>Pages#impressum</h1>
<p>Find me in app/views/pages/impressum.html.erb</p>

app/views/pages/kontakt.html.erb
<h1>Pages#kontakt</h1>
<p>Find me in app/views/pages/kontakt.html.erb</p>

app/views/pages/mitwirken.html.erb
<h1>Pages#mitwirken</h1>
<p>Find me in app/views/pages/mitwirken.html.erb</p>

app/views/pages/vision.html.erb
<h1>Pages#vision</h1>
<p>Find me in app/views/pages/vision.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>Folgende Fehler sind aufgetreten:</h2><br />
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Registrieren</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages' %>
  <div class="field">
    <%= f.label :name, "Nickname:" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email, "Emailadresse:" %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password, "Passwort:" %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Passwort bestätigen:" %><br />
    <%= f.password_field :password_confirmation %>
  </div><br />
  <div class="actions">
    <%= f.submit "Senden" %>
  </div>
<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Profile information">
  <tr>
    <td class="main">
      <h1>
        <%= @user.name %>
      </h1>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @user.name %><br />
      <strong>URL</strong>  <%= link_to user_path(@user), @user %>
    </td>
  </tr>
</table>